### ISSUE TITLE
Bug in fan control logic

### ISSUE THREAD

**Issue by khrystoph** [uptime-industries/compute-blade-pwm-fan-control#3]
Upon trying to use the fan control python script, it often fails (yes, I've verified I'm on the correct node as I've tried to run on both nodes and the first node instantly fails).

What happens is that when you run a few iterations of the program with a sleep timer of just 1, the fan speed controller runs into a stack trace fail that looks like this:

```
"fan_control.py" 53L, 1512B                                                               47,15         Bot
    if temperature > MIN_TEMP:
Traceback (most recent call last):
  File "/home/bret/compute-blade-pwm-fan-control/./fan_control.py", line 44, in <module>
    handleFanSpeed(fan, getCpuTemperature())
  File "/home/bret/compute-blade-pwm-fan-control/./fan_control.py", line 33, in handleFanSpeed
    fan.forward(FAN_LOW + delta * FAN_GAIN)
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 1385, in forward
    self.enable_device.value = speed
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 130, in __setattr__
    return super().__setattr__(name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 436, in value
    self._write(value)
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 422, in _write
    raise OutputDeviceBadValue("PWM value must be between 0 and 1")
gpiozero.exc.OutputDeviceBadValue: PWM value must be between 0 and 1
```

for some reason, when we're calling fan.forward, we're passing in a number that's not within the designated values of zero to one. The call back is here:
https://github.com/gpiozero/gpiozero/blob/master/gpiozero/output_devices.py#L1371

It sometimes takes a longer period of time, but eventually, it does crash.

When I print out the values of the thing crashing I get the following information:
```
$ ./fan_control.py
CPU temperature: 45.764 | fan low: 1 | delta: 0.7640000000000029 | fan gain:4.0 | value to forward: 4.056000000000012
```

Since the formula is FAN_LOW + delta * FAN_GAIN, I think the problem is forgetting to close the parenthesis around FAN_LOW and delta, no?

I'm going to test the fix of putting parenthesis around "FAN_LOW + delta" as I think that was the intended case to begin with.

https://github.com/uptime-industries/compute-blade-pwm-fan-control/blob/6d08a80cee511d91cc5f4ded0fb56a9e0a305764/fan_control.py#L30

**Comment by khrystoph** [comment]
oh, to reproduce what I found, I just used the following print statement on line 33:
```
        print("CPU temperature: {} | fan low: {} | delta: {} | fan gain:{} | value to forward: {}\n".format(temperature, FAN_LOW, delta, FAN_GAIN, (FAN_LOW + delta * FAN_GAIN)))
```

**Comment by khrystoph** [comment]
I've fixed the error, but I'm looking for a way to both read and write the RPMs in the same program (there's a GPIO busy signal if you try to run both the read and control at the same time).

Anyway, the fix in the code for this is going to take me a bit to go back and make some changes, but I think I can have it in a PR sometime in the next week or so.

Essentially, the process looks a bit like this:
```
FAN_GAIN = float(MAX_TEMP - OFF_TEMP)/ FAN_MAX
...
delta = temperature - OFF_TEMP
fan.forward(delta * FAN_GAIN)
```

The way you were doing the math, you could end up with some really strange outcomes where the speed is put in as a number > 1 or < 0, triggering an exception in the fan.forward() call.

I changed the call a bit because the percentage you want to set is the percent needed to get to the fan turning off. I also added an extra case to set minimum speed to 1% of max speed when it's under the MIN_TEMP with another elif section.

Since the logic is all contained in temperature > MIN_TEMP, the delta should ALWAYS be greater than 0 in that segment and it will get better cooling behavior if you use the OFF_TEMP to calculate the delta. Regardless, it'll drop the fan down to 1%. You could swap out the OFF_TEMP value in FAN_GAIN for MIN_TEMP, but that would be the only thing that should really be adjusted there, otherwise it tends to crash in unepected ways. This prevents that.
